apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: guess-postgres-data
  namespace: {{ .Release.Namespace }}
  labels:
    app: guess-postgres
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.postgres.storage }}
